### ISSUE TITLE
open link in new tab

### ISSUE THREAD

**Issue by msyahri** [devgossips/linktree#15]
Dear, thats verry awesome,
is there a way to make the social links open in a new tab?

**Comment by devgossips** [comment]
Yes possible 😅

**Comment by devgossips** [comment]
See I have made the changes @msyahri 
If you like this you may follow me on
twitter (https://twitter.com/heysagnik)

**Comment by msyahri** [comment]
very cool 👏🏼😀
Thank you so much

**Comment by devgossips** [comment]
If you find this helpful you may buy me a coffee ☕ 🙏🙏🙏https://www.buymeacoffee.com/devgossips
