### ISSUE TITLE
Add light mode 💡

### ISSUE THREAD

**Issue by devilraj98** [devgossips/linktree#6]

**Comment by ashalfarhan** [comment]
Can i grab this up? if there's no one is working on this.

**Comment by devgossips** [comment]
@ashalfarhan so I have assigned you.

**Comment by devgossips** [comment]
Issue solved

**Comment by devgossips** [comment]
hey @ashalfarhan  you made an error !!!!
![image](https://user-images.githubusercontent.com/70798495/140600033-eec82a48-05cd-4c52-9646-e82653203c03.png)
Can you see when you hover the mouse on any card its not showing properly ?
Please fix the issue !

**Comment by ashalfarhan** [comment]
Sorry, but i dont get your point, do you mean the font color?

**Comment by devgossips** [comment]
no  during light mode the hover is not noticeable 
![image](https://user-images.githubusercontent.com/70798495/140601497-9f1e1d66-90c0-4495-a388-69d8f0ed8156.png)

**Comment by oneamanish** [comment]
see my pull req.

**Comment by ashalfarhan** [comment]
@devgossips Is this issue already resolved? if it is, you can close this issue, right?

**Comment by devgossips** [comment]
Yes it's resolved
